name: Manual Test Execution

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Name of the test file to run (e.g., add_user.robot)'
        required: true
        type: string
        default: 'add_user.robot'
      scenario:
        description: 'Name of the scenario to run (e.g., "Cenário: 01 - Criar conta como administrador")'
        required: true
        type: string

jobs:
  manual-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Get Code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.12

    - name: Install Deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: rfbrowser init

    - name: List Test Scenarios
      id: list_scenarios
      run: |
        if [ -f tests/${{ github.event.inputs.test_file }} ]; then
          grep -E '^\*\*\* Test Cases \*\*\*' -A 20 tests/${{ github.event.inputs.test_file }}
        else
          echo "Test file not found!"
          exit 1
        fi

    - name: Run Specific Test with Scenario
      run: |
        if [ -f tests/${{ github.event.inputs.test_file }} ]; then
          robot -d ./logs -v BROWSER:chromium -v IS_HEADLESS:True --test "${{ github.event.inputs.scenario }}" tests/${{ github.event.inputs.test_file }}
        else
          echo "Test file not found!"
          exit 1
        fi

    - name: Robot Report 
      uses: joonvena/robotframework-reporter-action@v2.4
      if: always()
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: logs

    - name: Upload Report
      uses: actions/upload-artifact@v4.3.5
      with:
        name: Test Report for File ${{ github.event.inputs.test_file }}
        path: logs
