name: E2E Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:

    runs-on: ubuntu-latest  

    steps:
    - name: Get Code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setu Python
      uses: actions/setup-python@v5.2.0

      with:
        python-version: 3.12
        
   
